---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install InfluxDB
  hosts: monitor
  roles:
    - role: influxdb
  tags: influxdb

- name: Install Chronograf
  hosts: monitor
  roles:
    - role: kbrebanov.chronograf
  tags: chronograf

- name: Install Performance Co-Pilot
  hosts: hosts
  roles:
    - { role: pcp-ansible, pcp_install_webapi: false, tags: ["pcp"] }

- name: Install and Configure Telegraf
  hosts: hosts
  roles:
    - { role: rossmcdonald.telegraf, tags: ["telegraf"] }

- name: Install and Configure Telegraf for Ceph nodes
  hosts: ceph_all
  roles:
    - { role: rossmcdonald.telegraf, tags: ["telegraf_ceph"] }

- name: Install Rally
  hosts: monitor
  roles:
    - role: ansible-rally

- name: Install PerfkitBenchmarker
  hosts: monitor
  roles:
    - role: perfkitbenchmarker

- name: Install other miscellaneous perf tools
  hosts: all
  roles:
    - role: misc-perftools

- name: Deploy and configure reports server
  hosts: monitor
  roles:
    - role: reports-server
      live_hostname: "{{ ansible_default_ipv4.address}}.xip.io"
      domains:
        - "{{ ansible_default_ipv4.address}}.xip.io"
        - "www.{{ ansible_default_ipv4.address }}.xip.io"
        - "{{ ansible_em1.ipv4.address }}.xip.io"
        - "www.{{ ansible_em1.ipv4.address }}.xip.io"

- name: Install Vector
  hosts: monitor
  roles:
    - role: vector
